Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -211,17 +211,17 @@ jobs:
 
         # 创建 Release 并获取 Release ID
         RELEASE_RESPONSE=$(curl -X POST \
-          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
-        -d '{"tag_name": "${{ steps.generate_name.outputs.RELEASE_TAG }}", "name": "${{ steps.generate_name.outputs.RELEASE_NAME }}", "body": "CMCC RAX 3000M NAND firmware"}' \
-        "https://api.github.com/repos/$REPO/releases")
+           -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
+           -d '{"tag_name": "${{ steps.generate_name.outputs.RELEASE_TAG }}", "name": "${{ steps.generate_name.outputs.RELEASE_NAME }}", "body": "CMCC RAX 3000M NAND firmware"}' \
+           "https://api.github.com/repos/$REPO/releases")
     
         # 获取 Release ID
         RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r '.id')
 
         # 检查 RELEASE_ID 是否正确
         if [ "$RELEASE_ID" == "null" ]; then
-        echo "Release creation failed. Response: $RELEASE_RESPONSE"
-        exit 1
+          echo "Release creation failed. Response: $RELEASE_RESPONSE"
+         exit 1
         fi
 
         # 上传文件夹中的所有文件到该 Release
@@ -235,5 +235,6 @@ jobs:
         done
       env:
       # 使用 Personal Access Token 进行身份验证
-      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        GH_TOKEN: ${{ secrets.GH_TOKEN }}
+
 
